version: 2
jobs:
  build_linux:
    docker:
      - image: ubuntu:16.04
    steps:
      - run: |
             apt update 
             apt install -y curl clang cmake git uuid-dev libx11-xcb-dev libgl1-mesa-dev
             curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
             apt install -y git-lfs
      - checkout
      - run: |
             git lfs fetch
             git lfs checkout
             ./build_crossguid.sh
             ./build_opengex.sh
             ./build_zlib.sh
             ./build.sh
      - run: cmake --build ./build --target test
  build_macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: git lfs fetch
      - run: git lfs checkout
      - run: curl -L -o $(pwd)/MacPorts-2.4.2-10.12-Sierra.pkg https://github.com/macports/macports-base/releases/download/v2.4.2/MacPorts-2.4.2-10.12-Sierra.pkg
      - run: sudo installer -package $(pwd)/MacPorts-2.4.2-10.12-Sierra.pkg -target /
      - run: rm $(pwd)/MacPorts-2.4.2-10.12-Sierra.pkg
      - run: |
             export PATH=/opt/local/bin:/opt/local/sbin:$PATH 
             sudo -E port -q install cmake xorg-libX11 xorg-libxcb mesa libGLU
             ./build_crossguid.sh
             ./build_opengex.sh
             ./build_zlib.sh
             ./build.sh
             cmake --build ./build --target test
  build_android:
    working_directory: ~/project
    docker:
      - image: tim03/android-sdk-ndk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run: |
             curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
             sudo apt install -y git-lfs
      - checkout
      - run: |
             git lfs fetch
             git lfs checkout
             ./build_crossguid_android.sh
             ./build_opengex_android.sh
             ./build_zlib_android.sh
             ./build_android.sh
      - restore_cache:
          key: jars-{{ checksum "Platform/Android/build.gradle" }}-{{ checksum  "Platform/Android/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
                   sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
                   ./gradlew androidDependencies
          working_directory: Platform/Android
      - save_cache:
          paths:
            - Platform/Android/.gradle
          key: jars-{{ checksum "Platform/Android/build.gradle" }}-{{ checksum  "Platform/Android/app/build.gradle" }}
      - run:
          name: Run Tests
          command: |
                   ./gradlew build
          working_directory: Platform/Android
      - store_artifacts:
          path: Platform/Android/app/build/reports
          destination: reports
      - store_artifacts:
          path: Platform/Android/app/build/test-results
          destination: test-results
      - store_artifacts:
          path: Platform/Android/app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: build/Test
          destination: engine-tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux
      - build_macos
      - build_android

